openapi: '3.0.1'
info:
  title: invoice management system – invoice generation
  description: Endpoints for generating PDF and ZUGFeRD invoices.
  version: 1.0.0

servers:
  - url: 'http://localhost:8080/invoice-management-system/api/'
    description: local server

paths:

  /v1/generateInvoicePDF/{cardmarketExternalOrderId}:
    get:
      tags:
        - InvoiceGenerationPDF
      summary: Generate and save an invoice in pdf format
      description: Generate an invoice in pdf format and returns it for saving on the client's machine.
      operationId: getInvoicePDF
      parameters:
        - name: cardmarketExternalOrderId
          in: path
          required: true
          description: The external order id.
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: PDF file generated successfully.
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '500':
          description: Server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error occurred while generating the PDF.

  /v1/generateInvoicesPDF/{startDate}/{endDate}:
    get:
      tags:
        - InvoiceGenerationPDF
      summary: Download invoices as a ZIP file
      description: Generates multiple invoices in PDF format and compresses them into a ZIP file.
      operationId: getInvoicesPDF
      parameters:
        - name: startDate
          in: path
          required: true
          schema:
            type: string
            format: date
          description: Start date of the period (YYYY-MM-DD)
        - name: endDate
          in: path
          required: true
          schema:
            type: string
            format: date
          description: End date of the period (YYYY-MM-DD)
      responses:
        '200':
          description: ZIP file containing invoices
          content:
            application/zip:
              schema:
                type: string
                format: byte

  /v1/generateInvoiceZUGFeRD/{cardmarketExternalOrderId}:
    get:
      tags:
        - InvoiceGenerationZUGFeRD
      summary: Generate and save an invoice in ZUGFeRD format
      description: Generate an invoice in ZUGFeRD format and returns it for saving on the client's machine.
      operationId: getInvoiceZUGFeRD
      parameters:
        - name: cardmarketExternalOrderId
          in: path
          required: true
          description: The external order id.
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: ZUGFeRD file generated successfully.
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '500':
          description: Server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error occurred while generating the Invoice.
