import React, { useState } from 'react';
import {
    Alert,
    Box,
    Button,
    Chip,
    CircularProgress,
    Dialog,
    DialogActions,
    DialogContent,
    DialogTitle,
    Divider,
    IconButton,
    MenuItem,
    Stack,
    TextField,
    Tooltip,
    Typography,
} from '@mui/material';
import ReceiptLongIcon from '@mui/icons-material/ReceiptLong';
import AddIcon from '@mui/icons-material/Add';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline';
import PublishIcon from '@mui/icons-material/Publish';
import AutoAwesomeOutlinedIcon from '@mui/icons-material/AutoAwesomeOutlined';
import NorthEastIcon from '@mui/icons-material/NorthEast';
import SouthEastIcon from '@mui/icons-material/SouthEast';
import KeyboardArrowDownIcon from '@mui/icons-material/KeyboardArrowDown';
import { useAtom } from 'jotai';
import { euerReportsAtom } from '../../store/Global';
import { EuerPosition, EuerReport, EuerSection } from '../../api/generated/Schemas';
import useEuer from '../../api/hooks/useEuer';
import useCreateEuer from '../../api/hooks/useCreateEuer';
import useDeleteEuer from '../../api/hooks/useDeleteEuer';
import usePublishEuer from '../../api/hooks/usePublishEuer';
import useAddEuerPosition from '../../api/hooks/useAddEuerPosition';
import useDeleteEuerPosition from '../../api/hooks/useDeleteEuerPosition';

// ─── Section definitions ─────────────────────────────────────────────────────

interface SectionDef {
    id: EuerSection;
    label: string;
    autoGenerated: boolean;
    isIncome: boolean;
}

const SECTIONS: SectionDef[] = [
    {
        id: EuerSection.BETRIEBSEINNAHMEN,
        label: 'Betriebseinnahmen',
        autoGenerated: true,
        isIncome: true,
    },
    {
        id: EuerSection.WAREN_ROHSTOFFE_HILFSSTOFFE,
        label: 'Waren, Rohstoffe und Hilfsstoffe einschließlich Nebenkosten',
        autoGenerated: true,
        isIncome: false,
    },
    {
        id: EuerSection.GERINGWERTIGE_WIRTSCHAFTSGUETER,
        label: 'Aufwendungen für geringwertige Wirtschaftsgüter',
        autoGenerated: false,
        isIncome: false,
    },
    {
        id: EuerSection.RECHTS_UND_STEUERBERATUNG,
        label: 'Kosten für Rechts- und Steuerberatung',
        autoGenerated: false,
        isIncome: false,
    },
    {
        id: EuerSection.BEITRAEGE_GEBUEHREN_ABGABEN_VERSICHERUNGEN,
        label: 'Beiträge, Gebühren, Abgaben und Versicherungen',
        autoGenerated: false,
        isIncome: false,
    },
    {
        id: EuerSection.ARBEITSMITTEL,
        label: 'Arbeitsmittel',
        autoGenerated: true,
        isIncome: false,
    },
    {
        id: EuerSection.VERPACKUNG_TRANSPORT,
        label: 'Kosten für Verpackung und Transport',
        autoGenerated: true,
        isIncome: false,
    },
    {
        id: EuerSection.UEBRIGE_BETRIEBSAUSGABEN,
        label: 'Übrige unbeschränkt abziehbare Betriebsausgaben',
        autoGenerated: false,
        isIncome: false,
    },
    {
        id: EuerSection.SONSTIGE_GRUNDSTUECKSAUFWENDUNGEN,
        label: 'Sonstige Aufwendungen für betrieblich genutzte Grundstücke',
        autoGenerated: false,
        isIncome: false,
    },
];

const CURRENT_YEAR = new Date().getFullYear();
const YEAR_OPTIONS = Array.from({ length: 10 }, (_, i) => CURRENT_YEAR - i);

// ─── Section card ─────────────────────────────────────────────────────────────

interface SectionCardProps {
    section: SectionDef;
    positions: readonly EuerPosition[];
    published: boolean;
    euerId: number;
    onAddClick: () => void;
    onDeletePosition: (positionId: number) => void;
    deletePositionLoading: boolean;
}

function SectionCard({
    section,
    positions,
    published,
    onAddClick,
    onDeletePosition,
    deletePositionLoading,
}: SectionCardProps) {
    const [collapsed, setCollapsed] = useState(false);
    const total = positions.reduce((sum, p) => sum + p.value, 0);

    return (
        <Box
            sx={{
                border: '1px solid',
                borderColor: 'divider',
                borderRadius: 2,
                bgcolor: 'background.paper',
                overflow: 'hidden',
            }}
        >
            {/* Header */}
            <Box
                sx={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: 1.5,
                    px: 2.5,
                    py: 1.5,
                    bgcolor: '#FAFAF8',
                    borderBottom: collapsed ? 'none' : '1px solid',
                    borderColor: 'divider',
                    cursor: 'pointer',
                    userSelect: 'none',
                }}
                onClick={() => setCollapsed((c) => !c)}
            >
                <Box sx={{ flex: 1, minWidth: 0 }}>
                    <Stack direction="row" alignItems="center" spacing={1} flexWrap="wrap">
                        <Typography variant="body2" fontWeight={600} sx={{ lineHeight: 1.4 }}>
                            {section.label}
                        </Typography>
                        {section.autoGenerated && (
                            <Chip
                                icon={<AutoAwesomeOutlinedIcon sx={{ fontSize: '12px !important' }} />}
                                label="Automatisch"
                                size="small"
                                variant="outlined"
                                sx={{
                                    fontSize: '0.65rem',
                                    height: 18,
                                    borderRadius: 1,
                                    color: 'text.secondary',
                                    borderColor: 'divider',
                                    '& .MuiChip-icon': { color: 'text.disabled' },
                                }}
                            />
                        )}
                    </Stack>
                </Box>
                <Typography
                    variant="body2"
                    fontWeight={700}
                    sx={{
                        flexShrink: 0,
                        color: section.isIncome
                            ? 'success.main'
                            : total > 0
                                ? 'text.primary'
                                : 'text.secondary',
                        minWidth: 80,
                        textAlign: 'right',
                    }}
                >
                    {total.toFixed(2)} €
                </Typography>
                <KeyboardArrowDownIcon
                    sx={{
                        fontSize: 18,
                        color: 'text.secondary',
                        flexShrink: 0,
                        transform: collapsed ? 'rotate(-90deg)' : 'rotate(0deg)',
                        transition: 'transform 0.2s ease',
                    }}
                />
            </Box>

            {/* Body */}
            {!collapsed && (
                <Box sx={{ px: 2.5, py: 1.5 }}>
                    {positions.length === 0 ? (
                        <Typography
                            variant="body2"
                            color="text.disabled"
                            sx={{ py: 0.5, fontStyle: 'italic' }}
                        >
                            {section.autoGenerated
                                ? 'Wird automatisch aus den Daten berechnet (Backend ausstehend)'
                                : 'Keine Positionen vorhanden'}
                        </Typography>
                    ) : (
                        <Stack divider={<Divider flexItem />}>
                            {positions.map((pos) => {
                                const canDelete = !pos.automaticallyCalculated && !published;
                                return (
                                    <Stack
                                        key={pos.id}
                                        direction="row"
                                        alignItems="center"
                                        justifyContent="space-between"
                                        sx={{ py: 0.75 }}
                                    >
                                        <Box sx={{ flex: 1, minWidth: 0, mr: 2 }}>
                                            <Typography variant="body2" noWrap>
                                                {pos.description}
                                            </Typography>
                                            {pos.automaticallyCalculated && (
                                                <Typography variant="caption" color="text.disabled">
                                                    Automatisch berechnet
                                                </Typography>
                                            )}
                                        </Box>
                                        <Stack direction="row" alignItems="center" spacing={0.5}>
                                            <Typography
                                                variant="body2"
                                                fontWeight={600}
                                                sx={{ minWidth: 70, textAlign: 'right' }}
                                            >
                                                {pos.value.toFixed(2)} €
                                            </Typography>
                                            {/* Only render delete button for manually added positions */}
                                            {!pos.automaticallyCalculated && (
                                                <Tooltip
                                                    title={
                                                        published
                                                            ? 'EÜR ist bereits veröffentlicht'
                                                            : 'Position löschen'
                                                    }
                                                >
                                                    <span>
                                                        <IconButton
                                                            size="small"
                                                            color="error"
                                                            onClick={() => onDeletePosition(pos.id!)}
                                                            disabled={published || deletePositionLoading}
                                                            aria-label="Position löschen"
                                                        >
                                                            <DeleteOutlineIcon sx={{ fontSize: 16 }} />
                                                        </IconButton>
                                                    </span>
                                                </Tooltip>
                                            )}
                                            {/* Placeholder spacing so layout stays consistent */}
                                            {pos.automaticallyCalculated && (
                                                <Box sx={{ width: 28 }} />
                                            )}
                                        </Stack>
                                    </Stack>
                                );
                            })}
                        </Stack>
                    )}

                    {!published && (
                        <Box sx={{ mt: 1.5, display: 'flex', justifyContent: 'flex-end' }}>
                            <Button
                                size="small"
                                variant="outlined"
                                startIcon={<AddIcon />}
                                onClick={(e) => {
                                    e.stopPropagation();
                                    onAddClick();
                                }}
                            >
                                Position hinzufügen
                            </Button>
                        </Box>
                    )}
                </Box>
            )}
        </Box>
    );
}

// ─── EÜR detail view ─────────────────────────────────────────────────────────

interface EuerDetailProps {
    entry: EuerReport;
    onBack: () => void;
    onEntryUpdated: (updated: EuerReport) => void;
    onEntryDeleted: () => void;
}

function EuerDetail({ entry, onBack, onEntryUpdated, onEntryDeleted }: EuerDetailProps) {
    const { handleDelete: deleteEuer, loading: deleteLoading } = useDeleteEuer();
    const { handlePublish, loading: publishLoading } = usePublishEuer();
    const { handleAdd, loading: addLoading, error: addError, setError: setAddError } = useAddEuerPosition();
    const { handleDelete: deletePosition, loading: deletePositionLoading } = useDeleteEuerPosition();

    const [addDialogSection, setAddDialogSection] = useState<EuerSection | null>(null);
    const [description, setDescription] = useState('');
    const [amount, setAmount] = useState('');
    const [deleteConfirmOpen, setDeleteConfirmOpen] = useState(false);
    const [publishConfirmOpen, setPublishConfirmOpen] = useState(false);

    const positions = entry.positions ?? [];
    const published = entry.published ?? false;

    const positionsForSection = (sectionId: EuerSection) =>
        positions.filter((p) => p.section === sectionId);

    const totalIncome = SECTIONS.filter((s) => s.isIncome).reduce(
        (sum, s) => sum + positionsForSection(s.id).reduce((a, p) => a + p.value, 0),
        0
    );
    const totalExpenses = SECTIONS.filter((s) => !s.isIncome).reduce(
        (sum, s) => sum + positionsForSection(s.id).reduce((a, p) => a + p.value, 0),
        0
    );
    const profit = totalIncome - totalExpenses;

    const handleAddSubmit = async () => {
        if (!addDialogSection) return;
        const parsedAmount = parseFloat(amount);
        if (!description.trim() || isNaN(parsedAmount) || parsedAmount < 0) return;
        const added = await handleAdd(entry.id!, addDialogSection, description.trim(), parsedAmount);
        if (added) {
            setDescription('');
            setAmount('');
            setAddDialogSection(null);
        }
    };

    const handleDeleteConfirmed = async () => {
        setDeleteConfirmOpen(false);
        const ok = await deleteEuer(entry.id!);
        if (ok) onEntryDeleted();
    };

    const handlePublishConfirmed = async () => {
        setPublishConfirmOpen(false);
        const updated = await handlePublish(entry.id!);
        if (updated) onEntryUpdated(updated);
    };

    const handleDeletePosition = async (positionId: number) => {
        await deletePosition(entry.id!, positionId);
    };

    return (
        <Stack spacing={3} width="100%">
            {/* Header */}
            <Box>
                <Stack direction="row" alignItems="center" justifyContent="space-between" flexWrap="wrap" gap={1}>
                    <Stack direction="row" alignItems="center" spacing={1.5}>
                        <Tooltip title="Zurück zur Übersicht">
                            <IconButton size="small" onClick={onBack} aria-label="Zurück">
                                <ArrowBackIcon fontSize="small" />
                            </IconButton>
                        </Tooltip>
                        <ReceiptLongIcon sx={{ color: 'primary.main', fontSize: 26 }} />
                        <Typography variant="h5">EÜR {entry.year}</Typography>
                        {published && (
                            <Chip
                                label="Veröffentlicht"
                                size="small"
                                color="success"
                                sx={{ fontWeight: 600, fontSize: '0.72rem' }}
                            />
                        )}
                    </Stack>
                    <Stack direction="row" spacing={1}>
                        {!published && (
                            <Button
                                variant="outlined"
                                color="primary"
                                size="small"
                                startIcon={publishLoading ? <CircularProgress size={14} /> : <PublishIcon />}
                                onClick={() => setPublishConfirmOpen(true)}
                                disabled={publishLoading}
                            >
                                Veröffentlichen
                            </Button>
                        )}
                        <Tooltip title={published ? 'Veröffentlichte EÜR kann nicht gelöscht werden' : 'EÜR löschen'}>
                            <span>
                                <Button
                                    variant="outlined"
                                    color="error"
                                    size="small"
                                    startIcon={deleteLoading ? <CircularProgress size={14} color="error" /> : <DeleteOutlineIcon />}
                                    onClick={() => setDeleteConfirmOpen(true)}
                                    disabled={published || deleteLoading}
                                >
                                    Löschen
                                </Button>
                            </span>
                        </Tooltip>
                    </Stack>
                </Stack>
                <Divider sx={{ mt: 2 }} />
            </Box>

            {/* Income sections */}
            <Box>
                <Typography variant="overline" color="text.secondary" sx={{ fontWeight: 600, letterSpacing: '0.08em' }}>
                    Einnahmen
                </Typography>
                <Stack spacing={1} sx={{ mt: 1 }}>
                    {SECTIONS.filter((s) => s.isIncome).map((section) => (
                        <SectionCard
                            key={section.id}
                            section={section}
                            positions={positionsForSection(section.id)}
                            published={published}
                            euerId={entry.id!}
                            onAddClick={() => setAddDialogSection(section.id)}
                            onDeletePosition={handleDeletePosition}
                            deletePositionLoading={deletePositionLoading}
                        />
                    ))}
                </Stack>
            </Box>

            {/* Expense sections */}
            <Box>
                <Typography variant="overline" color="text.secondary" sx={{ fontWeight: 600, letterSpacing: '0.08em' }}>
                    Ausgaben
                </Typography>
                <Stack spacing={1} sx={{ mt: 1 }}>
                    {SECTIONS.filter((s) => !s.isIncome).map((section) => (
                        <SectionCard
                            key={section.id}
                            section={section}
                            positions={positionsForSection(section.id)}
                            published={published}
                            euerId={entry.id!}
                            onAddClick={() => setAddDialogSection(section.id)}
                            onDeletePosition={handleDeletePosition}
                            deletePositionLoading={deletePositionLoading}
                        />
                    ))}
                </Stack>
            </Box>

            {/* Summary */}
            <Box
                sx={{
                    border: '1px solid',
                    borderColor: 'divider',
                    borderRadius: 2,
                    bgcolor: 'background.paper',
                    overflow: 'hidden',
                }}
            >
                <Box sx={{ px: 2.5, py: 1.5, bgcolor: '#FAFAF8', borderBottom: '1px solid', borderColor: 'divider' }}>
                    <Typography variant="body2" fontWeight={700}>Zusammenfassung</Typography>
                </Box>
                <Stack divider={<Divider flexItem />}>
                    <Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ px: 2.5, py: 1.25 }}>
                        <Stack direction="row" alignItems="center" spacing={1}>
                            <NorthEastIcon sx={{ fontSize: 16, color: 'success.main' }} />
                            <Typography variant="body2" color="text.secondary">Gesamteinnahmen</Typography>
                        </Stack>
                        <Typography variant="body2" fontWeight={600} color="success.main">
                            {totalIncome.toFixed(2)} €
                        </Typography>
                    </Stack>
                    <Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ px: 2.5, py: 1.25 }}>
                        <Stack direction="row" alignItems="center" spacing={1}>
                            <SouthEastIcon sx={{ fontSize: 16, color: 'error.main' }} />
                            <Typography variant="body2" color="text.secondary">Gesamtausgaben</Typography>
                        </Stack>
                        <Typography variant="body2" fontWeight={600} color="error.main">
                            {totalExpenses.toFixed(2)} €
                        </Typography>
                    </Stack>
                    <Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ px: 2.5, py: 1.5 }}>
                        <Typography variant="body2" fontWeight={700}>
                            {profit >= 0 ? 'Gewinn' : 'Verlust'}
                        </Typography>
                        <Typography variant="body1" fontWeight={700} color={profit >= 0 ? 'success.main' : 'error.main'}>
                            {profit.toFixed(2)} €
                        </Typography>
                    </Stack>
                </Stack>
            </Box>

            {/* Add position dialog */}
            <Dialog open={addDialogSection !== null} onClose={() => { setAddDialogSection(null); setAddError(''); }} maxWidth="xs" fullWidth>
                <DialogTitle>
                    Position hinzufügen
                    {addDialogSection && (
                        <Typography variant="body2" color="text.secondary" sx={{ mt: 0.5, fontWeight: 400 }}>
                            {SECTIONS.find((s) => s.id === addDialogSection)?.label}
                        </Typography>
                    )}
                </DialogTitle>
                <DialogContent>
                    <Stack spacing={2} sx={{ mt: 1 }}>
                        {addError && <Alert severity="error" onClose={() => setAddError('')}>{addError}</Alert>}
                        <TextField
                            label="Beschreibung"
                            value={description}
                            onChange={(e) => setDescription(e.target.value)}
                            size="small"
                            fullWidth
                            required
                            autoFocus
                        />
                        <TextField
                            label="Betrag (€)"
                            value={amount}
                            onChange={(e) => setAmount(e.target.value)}
                            size="small"
                            fullWidth
                            required
                            type="number"
                            inputProps={{ min: 0, step: '0.01' }}
                        />
                    </Stack>
                </DialogContent>
                <DialogActions>
                    <Button onClick={() => { setAddDialogSection(null); setAddError(''); }}>Abbrechen</Button>
                    <Button
                        variant="contained"
                        onClick={handleAddSubmit}
                        disabled={addLoading || !description.trim() || !amount || parseFloat(amount) < 0}
                        startIcon={addLoading ? <CircularProgress size={14} color="inherit" /> : undefined}
                    >
                        Hinzufügen
                    </Button>
                </DialogActions>
            </Dialog>

            {/* Delete confirm dialog */}
            <Dialog open={deleteConfirmOpen} onClose={() => setDeleteConfirmOpen(false)} maxWidth="xs" fullWidth>
                <DialogTitle>EÜR löschen?</DialogTitle>
                <DialogContent>
                    <Typography variant="body2" color="text.secondary">
                        Die EÜR {entry.year} wird unwiderruflich gelöscht. Alle manuell erfassten Positionen gehen verloren.
                    </Typography>
                </DialogContent>
                <DialogActions>
                    <Button onClick={() => setDeleteConfirmOpen(false)}>Abbrechen</Button>
                    <Button variant="contained" color="error" onClick={handleDeleteConfirmed}>
                        Löschen
                    </Button>
                </DialogActions>
            </Dialog>

            {/* Publish confirm dialog */}
            <Dialog open={publishConfirmOpen} onClose={() => setPublishConfirmOpen(false)} maxWidth="xs" fullWidth>
                <DialogTitle>EÜR veröffentlichen?</DialogTitle>
                <DialogContent>
                    <Typography variant="body2" color="text.secondary">
                        Die EÜR {entry.year} wird veröffentlicht. Danach können keine Positionen mehr hinzugefügt oder gelöscht werden.
                    </Typography>
                </DialogContent>
                <DialogActions>
                    <Button onClick={() => setPublishConfirmOpen(false)}>Abbrechen</Button>
                    <Button variant="contained" onClick={handlePublishConfirmed}>
                        Veröffentlichen
                    </Button>
                </DialogActions>
            </Dialog>
        </Stack>
    );
}

// ─── List view ────────────────────────────────────────────────────────────────

export default function Euer() {
    useEuer();

    const [euerReports] = useAtom(euerReportsAtom);
    const { handleCreate, loading: createLoading, error: createError, setError: setCreateError } = useCreateEuer();

    const [createDialogOpen, setCreateDialogOpen] = useState(false);
    const [selectedYear, setSelectedYear] = useState<number>(CURRENT_YEAR);
    const [selectedEntry, setSelectedEntry] = useState<EuerReport | null>(null);

    const handleOpenCreate = () => {
        const nextYear = YEAR_OPTIONS.find((y) => !euerReports.some((e) => e.year === y)) ?? CURRENT_YEAR;
        setSelectedYear(nextYear);
        setCreateError('');
        setCreateDialogOpen(true);
    };

    const handleCreate_ = async () => {
        const ok = await handleCreate(selectedYear);
        if (ok) setCreateDialogOpen(false);
    };

    const alreadyExists = euerReports.some((e) => e.year === selectedYear);

    // Keep local selectedEntry in sync after publish/delete operations update the atom
    const syncedEntry = selectedEntry
        ? (euerReports.find((r) => r.id === selectedEntry.id) ?? null)
        : null;

    // ── Detail view ──────────────────────────────────────────────────────────
    if (syncedEntry) {
        return (
            <EuerDetail
                entry={syncedEntry}
                onBack={() => setSelectedEntry(null)}
                onEntryUpdated={(updated) => setSelectedEntry(updated)}
                onEntryDeleted={() => setSelectedEntry(null)}
            />
        );
    }

    // ── List view ────────────────────────────────────────────────────────────
    return (
        <Box style={{ width: '100%' }}>
            <Stack spacing={3} width="100%">
                <Box>
                    <Stack direction="row" alignItems="center" justifyContent="space-between">
                        <Stack direction="row" alignItems="center" spacing={1.5}>
                            <ReceiptLongIcon sx={{ color: 'primary.main', fontSize: 28 }} />
                            <Typography variant="h5">EÜR</Typography>
                            {euerReports.length > 0 && (
                                <Chip
                                    label={euerReports.length}
                                    size="small"
                                    color="primary"
                                    sx={{ fontWeight: 600, borderRadius: 1 }}
                                />
                            )}
                        </Stack>
                        <Button
                            variant="outlined"
                            color="primary"
                            size="small"
                            startIcon={<AddIcon />}
                            onClick={handleOpenCreate}
                        >
                            Neue EÜR
                        </Button>
                    </Stack>
                    <Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>
                        Einnahmen-Überschuss-Rechnung je Kalenderjahr
                    </Typography>
                    <Divider sx={{ mt: 2 }} />
                </Box>

                {euerReports.length === 0 ? (
                    <Box
                        sx={{
                            border: '1px dashed',
                            borderColor: 'divider',
                            borderRadius: 2,
                            py: 6,
                            display: 'flex',
                            flexDirection: 'column',
                            alignItems: 'center',
                            gap: 1.5,
                        }}
                    >
                        <ReceiptLongIcon sx={{ fontSize: 40, color: 'text.disabled' }} />
                        <Typography variant="body2" color="text.secondary">
                            Noch keine EÜR vorhanden
                        </Typography>
                        <Button
                            variant="outlined"
                            size="small"
                            startIcon={<AddIcon />}
                            onClick={handleOpenCreate}
                        >
                            Erste EÜR anlegen
                        </Button>
                    </Box>
                ) : (
                    <Stack spacing={0.75}>
                        {euerReports.map((entry) => (
                            <Box
                                key={entry.id}
                                sx={{
                                    border: '1px solid',
                                    borderColor: 'divider',
                                    borderRadius: 2,
                                    bgcolor: 'background.paper',
                                    display: 'flex',
                                    alignItems: 'center',
                                    gap: 1.5,
                                    px: 2,
                                    py: 1.25,
                                    transition: 'border-color 0.15s ease',
                                    '&:hover': { borderColor: 'rgba(61,107,82,0.35)' },
                                }}
                            >
                                <Box sx={{
                                    width: 36, height: 36, borderRadius: 1.5,
                                    bgcolor: 'rgba(61,107,82,0.08)',
                                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                                    color: 'primary.main', flexShrink: 0,
                                }}>
                                    <ReceiptLongIcon sx={{ fontSize: 18 }} />
                                </Box>

                                <Box sx={{ flex: 1 }}>
                                    <Stack direction="row" alignItems="center" spacing={1}>
                                        <Typography variant="body2" fontWeight={600}>
                                            EÜR {entry.year}
                                        </Typography>
                                        {entry.published && (
                                            <Chip
                                                label="Veröffentlicht"
                                                size="small"
                                                color="success"
                                                sx={{ fontSize: '0.65rem', height: 18, borderRadius: 1 }}
                                            />
                                        )}
                                    </Stack>
                                    <Typography variant="caption" color="text.secondary">
                                        {(entry.positions ?? []).length} Positionen
                                        {entry.createdAt && ` · Erstellt am ${entry.createdAt}`}
                                    </Typography>
                                </Box>

                                <Button
                                    variant="outlined"
                                    size="small"
                                    onClick={() => setSelectedEntry(entry)}
                                >
                                    Öffnen
                                </Button>
                            </Box>
                        ))}
                    </Stack>
                )}
            </Stack>

            {/* Create dialog */}
            <Dialog open={createDialogOpen} onClose={() => setCreateDialogOpen(false)} maxWidth="xs" fullWidth>
                <DialogTitle>Neue EÜR anlegen</DialogTitle>
                <DialogContent>
                    <Stack spacing={2} sx={{ mt: 1 }}>
                        {createError && (
                            <Alert severity="error" onClose={() => setCreateError('')}>{createError}</Alert>
                        )}
                        <TextField
                            select
                            label="Jahr"
                            value={selectedYear}
                            onChange={(e) => setSelectedYear(Number(e.target.value))}
                            size="small"
                            fullWidth
                            error={alreadyExists}
                            helperText={alreadyExists ? 'Für dieses Jahr existiert bereits eine EÜR.' : ''}
                        >
                            {YEAR_OPTIONS.map((year) => (
                                <MenuItem key={year} value={year}>{year}</MenuItem>
                            ))}
                        </TextField>
                    </Stack>
                </DialogContent>
                <DialogActions>
                    <Button onClick={() => setCreateDialogOpen(false)}>Abbrechen</Button>
                    <Button
                        variant="contained"
                        onClick={handleCreate_}
                        disabled={alreadyExists || createLoading}
                        startIcon={createLoading ? <CircularProgress size={14} color="inherit" /> : undefined}
                    >
                        Anlegen
                    </Button>
                </DialogActions>
            </Dialog>
        </Box>
    );
}
